### PR TITLE
PX4: SBUS RSSI/Link Quality code - Resubmit #1

### PR DESCRIPTION
**Pull request by StewLG**
(This is a resbumit of https://github.com/diydrones/PX4Firmware/pull/38.)

This counts recent (about 0.7 seconds worth) of SBUS frames to see how many have been dropped, and calculates a Link Quality metric as a percentage of the possible total. This allows any SBUS radio receiver to offer an RSSI-type value to ArduPilot without resorting to additional channels or FrSky style telemetry wiring.

AP_HAL has had one function added to the interface. It has been stubbed out everywhere except PX4, although there are other platforms that could likely support it - the Linux boards for example.

Closes diydrones/ardupilot#2721.
Enables https://github.com/diydrones/ardupilot/pull/3274 (see for more details).

### CODE REVIEW

**Comment by magicrub** [comment]
@tridge please look into this for v3.5.1 release

**Comment by StewLG** [comment]
@magicrub This has been rebased and is ready for review. No changes since last time. Enables https://github.com/ArduPilot/ardupilot/pull/3274.  

(I'm not the best at Git/GitHub so please be patient if I've made a mess here.)

**Comment by magicrub** [comment]
Anything that touches PX4Firmware needs to be run by @tridge because he's doing a huge refactor. This is a very old PR, thank you for hanging in there! I'll remind him take a look.

**Comment by StewLG** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/6467

**Pull request closed without merging**
