### PR TITLE
SRXL support added for Multiplex SRXL v1-12channel and v2-16channel

### PR DESCRIPTION
**Pull request by RomanSeb**
**New SRXL library**

_Description_
In order to use Muliplex receivers on the Pixhawk DSM port, I implemented Multiplex SRXL support.
Only two files have been changed:
 - srxl.c
 - srxl.h

The new implementation distinguishes between SRXL variants by evaluating two characteristics that are unique to each SRXL variant:
 - The Header Byte
 - The number of bytes for one SRXL frame
Additionally SRXL implements a CRC that is checked by the implementation to ensure valid data and in this case freedom from interference.

These SRXL variants are now implemented:
 - Multiplex SRXL v1 / JR PROPO  X-Bus Mode B 
 - Multiplex SRXL v2 
 - Spektrum SRXL as implemented by Tridge for the AR7700 receiver

The new implementation is lightweight and has been written to make it easy to implement more SRXL variants in the future.

_Testing for Multiplex SRXL v1_
I tested the implementation with an USB-Serial adapter attached to a Multiplex RX-9-DR M-Link receiver by using a modified version of the testbench (inside the srxl.c file) provided by Tridge. I also created the firmware for a pixhawk equipped quad and tested the response to the transmitter in MissionPlanner (not in flight).
--> Both tests were successful. The displayed values for the RC channels match the input on the transmitter.

_Todo_
Unfortunately I had to relocate the Spektrum SRXL code from Tridge inside the srxl.c file (without major changes) and I cant verify if it is still working.  I also do not own a Multiplex receiver that implements SRXLv2 so I could not test this variant. These points are on the todo list.
 - Test with Multiplex SRXL v2 receiver (16 channel)
 - New test with Spektrum AR7700 receiver (Sorry Tridge, I know you tested it before)

BR

### CODE REVIEW

**Comment by RomanSeb** [comment]
**Multiplex SRXLv1 test**
srxlv1-test

**Comment by tridge** [comment]
very nice work, thanks!
applied

**Comment by tridge** [comment]
I've pushed in some minor fixes for the v5 protocol varient
https://github.com/ArduPilot/PX4Firmware/commit/b1f8c553cf1a797cce1916b946999fc141e093ca

**Comment by RomanSeb** [comment]
Thanks for merging.

Von: Andrew Tridgell [mailto:notifications@github.com]
Gesendet: Donnerstag, 24. November 2016 11:45
An: ArduPilot/PX4Firmware <PX4Firmware@noreply.github.com>
Cc: RomanSeb <roman-29188@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [ArduPilot/PX4Firmware] SRXL support added for Multiplex SRXL v1-12channel and v2-16channel (#70)


very nice work, thanks!
applied

**Pull request merged**
