### PR TITLE
F4BY HAL

### PR DESCRIPTION
**Pull request by mstrinzha**
Support for F4BY board. More detail are here: http://diydrones.com/forum/topics/f4by-controller-with-arducopter-3-3-2-arduplane-3-4-tested

### CODE REVIEW

**Comment by mstrinzha** [comment]
Code is updated.

**Comment by mstrinzha** [comment]
@OXINARF any comments?

**Comment by OXINARF** [comment]
Not really, this has to go through @tridge. He is unfortunately quite busy.

**Comment by auturgy** [comment]
Suggest close - overtaken by https://github.com/ArduPilot/ardupilot/pull/7999

**Comment by OXINARF** [comment]
Agreed, closed.

**Pull request closed without merging**
